{% set name = "python-multipart" %}
{% set version = "0.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/python_multipart/python_multipart-{{ version }}.tar.gz
  sha256: 8dd0cab45b8e23064ae09147625994d090fa46f5b0d1e13af944c331a7fa9d13

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - hatchling
    - python
    - pip
  run:
    - python

test:
  imports:
    - multipart
  requires:
    - pip
  commands:
    - pip check
  # downstreams:
  #   - starlette-full
  #   # Skip py<312 because of incompatible pydantic version:
  #   # "TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'"
  #   - lightning  # [py<312]
  #   - lightning-cloud

about:
  home: https://github.com/Kludex/python-multipart
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A streaming multipart parser for Python.
  description: |
    python-multipart is an Apache2 licensed streaming multipart parser for Python.
  doc_url: https://kludex.github.io/python-multipart/
  dev_url: https://github.com/Kludex/python-multipart

extra:
  recipe-maintainers:
    - carlodri
