{% set name = "python-multipart" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/python_multipart/python_multipart-{{ version }}.tar.gz
  sha256: 7a68db60c8bfb82e460637fa4750727b45af1d5e2ed215593f917f64694d34fe

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python

test:
  imports:
    - multipart
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Kludex/python-multipart
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A streaming multipart parser for Python.
  description: |
    python-multipart is an Apache2 licensed streaming multipart parser for Python.
  doc_url: https://kludex.github.io/python-multipart/
  dev_url: https://github.com/Kludex/python-multipart

extra:
  recipe-maintainers:
    - carlodri
