{% set name = "python-multipart" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/python_multipart/python_multipart-{{ version }}.tar.gz
  sha256: 03f54688c663f1b7977105f021043b0793151e4cb1c1a9d4a11fc13d622c4026

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - hatchling
    - python
    - pip
  run:
    - python

test:
  imports:
    - multipart
  requires:
    - pip
  commands:
    - pip check
  downstreams:
    - starlette-full
    - lightning
    - lightning-cloud

about:
  home: https://github.com/andrew-d/python-multipart
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A streaming multipart parser for Python.
  description: |
    python-multipart is an Apache2 licensed streaming multipart parser for Python.
    It's still under some development, but test coverage is currently 100%.
    Documentation is available [here](http://andrew-d.github.io/python-multipart/).
  doc_url: https://andrew-d.github.io/python-multipart/
  dev_url: https://github.com/andrew-d/python-multipart

extra:
  recipe-maintainers:
    - carlodri
