{% set name = "python-multipart" %}
{% set version = "0.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/python_multipart/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: 7340bef99a7e0032613f56dc36027b959fd3b30a787ed62d310e951f7c3a3a58

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - hatchling
    - python
    - pip
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - multipart
  requires:
    - pip
    - pytest >=8.1.1
    - pyyaml >=6.0.1
  commands:
    - pip check
    - set PYTHONUTF8=1              # [win]
    - set PYTHONIOENCODING="UTF-8"  # [win]
    - pytest -vv tests

about:
  home: https://github.com/Kludex/python-multipart
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A streaming multipart parser for Python.
  description: |
    python-multipart is an Apache2 licensed streaming multipart parser for Python.
  doc_url: https://kludex.github.io/python-multipart
  dev_url: https://github.com/Kludex/python-multipart

extra:
  recipe-maintainers:
    - carlodri
