travis:
  secure:
    BINSTAR_TOKEN: RPwVEjTItNHaW3Nh1KcfbW3XqT1bRutXkQ8LFuREdpnMMT7QgGW1DIIyIIPx79LxpQxIxwYyMpFAOoFuyz42cBVSzDL2O/q328BEJvLn5NXuPFUPVEYoLORayuarXSCrUptW4+rP62+i992jHnM89kK6nfuwMB+Y41Ufp+e2uU/e0NO0tpDLZ7b2PKpcn51NrsRjOZSRYFKFd88v5c3sYKIMjLam+eJqieugXynr5bXiknraJqFWdk7CPabWWrqM0FSCT+FYsBsUk3K2gc6SPEJEj6VePO0P8sfpnL0XHDW1Ijr9k6mlCS1QOAupPbGzpn8AKNfSNOdzeFsEaca/0XyWIdhTDqrq33x9obrzZ1evls9CjBM88fyphYMAD0jnIdtzf1PtnvepqEH5iQ5idKbSyC3UDpGau7yEpOQZYE1xwKBMsRYTsd/ZLR4WQSxRlZx7M0QLzpXHGmpDHwaWUSCRmNSERCRECteGlqEoGo0w0xn0Wzf7TCgj9IHn7f98MBU+Vj5FquGTg2EJa5vLoT2Zm3VF9VaJDkqLWIKzHPcYyzOUFGI7nVR6vT5bZn1Ts1f5hLb9od+5vngD7AToXoPO/pcKvpmDT9m312gdhH4YdJ4Utl8WQF4PmlEFQKhbO2dJS65Lak5yVwdbSwGWVO5/X7Ie/O/5XGr2WaSJO6s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
