travis:
  secure:
    BINSTAR_TOKEN: W/qe1NlTJPwlWBk/QJH9UyoEwnNZ2UxhjymSsw2limg2gHDt01OE1xCG+1uJrpgtY1oP0tmqn/z1E769Jc/ear8g9nFb0SNvH9V7pWK2eXdaFpsgpzFt6R09Dxyoyi5ufMEyrWYyzkFasDdl4byk/PT0HI6uwpkvmAEpXzJrlo94OGloEk3Y1igZHhAy8QJyJm4Jk6orIDuX4//UG/7hmwoGnDU+F03hGSMOMl1eYSL+/6OM2omRNCvk5Un9FiGAYuQiSqVcRg5KaHQYBhuyqLmFNwlkbzjRPh5bRmnyE4Qqjb9cZeD7t0ETGH8W4FtF0808firHcw52Hwc7zUMQASYjmTsFlWWnKVmzAAE8Qr98eIRfyRGNOGUr5w+7X8egVEZJNxq+fX8IWe8AY8ZsrHdaY/EhzC+330Lfww6AEZU5jf7Y3jjRagSp+qu1BEOX8bcMtxJsYHMh7vgPVSYiM487sdhOUdbpffK1zcg4eaJoxEkKsqVpEtSYW18DD6qq7ILAb46b8Rn/udRU509oCNPSdTsJnTpf/9YM2RrCjRxGmSPGbl/QtEU5uvuaz1Cqv5s78UVWi7MNQsET05bpLnRZBR4h1ck/lZSi5I0r7A5nBTuafYsQ1WqgmxJnNm+03tiBeAH5pbUz727X5ETzMegTfH3WYiXnjxah5sohvD4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
